### ISSUE TITLE
Mock gw.api.database.Query not work

### ISSUE THREAD

**Issue by pelesit** [gosu-lang/gosu-lang#92] opened 2016-11-15 12:49 UTC
We are trying to mock the gw.api.database.Query class to could mock some database calls. 
But the line 
**var mockQuery = Mockito.mock(Query)** gives me this error:

java.lang.NullPointerException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at gw.internal.gosu.parser.MethodJavaClassMethod.invoke(MethodJavaClassMethod.java:126)
	at com.guidewire.commons.entity.type2.EntityPropertyAccessorBase.invokeMethod(EntityPropertyAccessorBase.java:106)
	at com.guidewire.commons.entity.type2.EntityPropertyAccessorBase.setValue(EntityPropertyAccessorBase.java:48)
	at gw.internal.gosu.runtime.GosuRuntimeMethods.setProperty(GosuRuntimeMethods.java:119)
	at program_.__Program__2309.evaluate(Unknown Source)
	at gw.internal.gosu.parser.GosuProgram.runProgram(GosuProgram.java:421)
	at gw.internal.gosu.parser.GosuProgram.evaluate(GosuProgram.java:253)
	at gw.internal.gosu.parser.GosuProgram_Proxy.evaluate(gw.internal.gosu.parser.GosuProgram_Proxy:2)
	at gw.internal.gosu.parser.ExecutionEnvironment$1.evaluate(ExecutionEnvironment.java:543)
	at gw.internal.gosu.parser.ExecutionEnvironment$1.runScript(ExecutionEnvironment.java:523)
	at gw.internal.gosu.parser.ExecutionEnvironment$1.run(ExecutionEnvironment.java:489)
	at java.lang.Thread.run(Thread.java:745)

**Comment by DPUkyle** [comment] 2017-03-28 16:43
Try running this in a test class, rather than than in a Gosu Program/Scratchpad. You may see different results.

**Comment by DPUkyle** [comment] 2017-03-30 22:38
Executed the above in a Guidewire "Gosu Scratchpad", connected to a live server in debug mode with DCEVM enabled. Could not reproduce the ST. Closing issue.

**Closed by DPUkyle** 2017-03-30 22:38 UTC
